#!/bin/bash
# This hook is run after a new virtualenv is activated.

#if  [[ ${VIRTUAL_ENV} == ${WORKON_HOME}/TEMP__* ]];
#then
#    pip install tox
#    pip install -U pip
#fi

if  [ -f ${WORKON_HOME}/distribute*.* ];
then
    rm ${WORKON_HOME}/distribute*.*
fi
pip install -U pip ipython ipdb requests
pip install git+https://github.com/saxix/cookiecutter.git@work#egg=cookiecutter
