#!/bin/bash
# This hook is run after a new virtualenv is activated.

if  [[ ${VIRTUAL_ENV} == ${WORKON_HOME}/TEMP__* ]];
then
    return
fi

pip install -U pip

if [[ ! -e ${VIRTUAL_ENV}/.project ]];then
	echo $PWD > ${VIRTUAL_ENV}/.project
fi

#if [[ $PWD == *ONU* ]]; then
#	pip install pytest requests setuptools cookiecutter tox
#fi
