#!/bin/bash
# This hook is run after every virtualenv is activated.

if [ -e $VIRTUAL_ENV/.project ]; then
    cd `cat $VIRTUAL_ENV/.project`
fi

export PATH=${PWD}/node_modules/.bin:$PATH

if [ -e ${PWD}/.virtualenv_hooks/postactivate ]; then
    . ${PWD}/.virtualenv_hooks/postactivate
fi
